### ISSUE TITLE
建议使用jwt来验证用户，避免对kv的操作

### ISSUE THREAD

**Issue by 14790897** [HuaTru/coco-cf-work#4]
jwt不需要数据库

**Comment by HuaTru** [comment]
这个我就先给你关了哈  你之后先往web-worker分支提交 我跟甘佬说一下看看他用不用得到页面

**Comment by HuaTru** [comment]
甘佬表示很感谢 但现在暂时不需要搞成页面
在一个呢 jwt 其实不需要的  而且也避免不了kv操作   而且也不授权发放

**Comment by 14790897** [comment]
授权操作由oauth完成，但返回的数据可以使用jwt将它们加密，只有服务器能验证（使用密钥解密），这种特性使得jwt可以作为用户验证的token而不需要数据库
```
  const payload = {
    userId: userId,
    req_v1_count: data.req_v1_count + 1, 
  };
```
比如这段信息可以使用jwt加密给用户，用户每次请求需要发送，而服务器使用密钥解密得到数据并验证，无需数据库

**Comment by HuaTru** [comment]
你怎么确定解析出来的数据是正常获取的token存放到kv保持 不是瞎造的呢
若是不与数据库进行数据比对 我是不是可以直接写成等级4呢

**Comment by 14790897** [comment]
jwt不能修改的

**Comment by HuaTru** [comment]
不好意思 记错了 jwt是可以被劫持修改的 只要服务端的签名密钥不泄露 修改是无效的
我刚查了下cf的文档  他是有jwt的库的 若是可以用的话 那这一步的查询是可以省略的
![image](https://github.com/HuaTru/coco-cf-work/assets/157573327/edb4cd66-7d8d-4516-bbee-ee773a2b31da)

**Comment by 14790897** [comment]
减少了两个数据库操作
```
  await setCache(`cctokenUser_${token}`, userId, OAUTH_TOKENS);
  await setCache(`cctokenUser_${userId}`, token, OAUTH_TOKENS);
```

**Comment by 14790897** [comment]
好不好？

**Comment by 14790897** [comment]
![image](https://github.com/HuaTru/coco-cf-work/assets/121866954/4af10ce3-3b52-4512-a993-9212a652d8fe)

**Comment by HuaTru** [comment]
好的 但这里处理需要明天我进行处理 或者你对这部分进行更改

**Comment by 14790897** [comment]
直接用我的分支

**Comment by HuaTru** [comment]
请注意实际需求  上面我跟您这边说过了 是不要页面的
而且您这边的分支 还需要构建推送到cf
与实际应用需求(直接可用)不符

**Comment by 14790897** [comment]
wrangler比打开cf粘贴代码方便多了

**Comment by HuaTru** [comment]
甘佬不会代码啊  这个不能只考虑开发的
而且这个方案估计很快就废弃转应用部署了(限制太多)
总不能让甘佬每次都问咋发吧

**Comment by 14790897** [comment]
真的很方便，废弃了为什么还在研究？

# 本地开发
```
npm install
//第一次需要进行登录
wrangler login
wrangler dev
```

# 部署

wrangler kv:namespace create "oauth_tokens"
wrangler kv:namespace create "user_data"  
wrangler kv:namespace create "cocopilot"
每次创建KV会返回对应的ID
要修改wrangler.toml中的对应KV的ID
然后
wrangler deploy

**Comment by HuaTru** [comment]
我说废弃 说的是估计
因为现在这个没什么可搞的了 限制太多  但没说不用
我知道很方便 但你不能要求不会开发的业务人员来自己编译上传 这是不合理的

**Comment by HuaTru** [comment]
你的想法跟我们这边实际需求是不太符合的  但你提供的jwt思路我们会进行采纳适配
其余的你可以在你自己的仓库上进行你想法的开发  想推送的话 我上面也单独开了个分支给你了
